[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 